version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Meni1971
      MYSQL_DATABASE: niloosapi
      MYSQL_USER: niloosapi
      MYSQL_PASSWORD: niloosapi
      #MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db-niloosapi:/var/lib/mysql
    networks:
      - back-niloosapi
  adminer:
    image: adminer
    depends_on: 
      - db
    restart: always
    ports:
      - 8088:8080
    networks:
      - back-niloosapi
  php:
    image: yiisoftware/yii2-php:7.3-apache
    depends_on: 
      - db
    environment: 
      - PHP_ENABLE_XDEBUG=1
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    networks:
      - back-niloosapi
volumes:
  db-niloosapi:
networks:
  back-niloosapi: