version: '3'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
      - '9005:9005'
    networks:
      - nlsapinet
networks:
  nlsapinet:
